#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MultiMedia.Resource", IsApplication=true)]

namespace MultiMedia
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int androidcolors = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int red = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int acousticbreeze = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int audiobkg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int happiness = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int img_174171 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pause_button_png_image_80706 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int play_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int prev_song = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int record_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int stop = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sweet = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int artwork = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int back = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int btnMusicPlayer = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int btnSoundRecorder = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int btnVideoPlayer = 2131230725;
			
			// aapt resource value: 0x7f080013
			public const int controlSet1 = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int controlSet2 = 2131230742;
			
			// aapt resource value: 0x7f080019
			public const int controlSet3 = 2131230745;
			
			// aapt resource value: 0x7f080012
			public const int controlsLt = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int fileBtn = 2131230740;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f08000d
			public const int nextSong = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int pause = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int play = 2131230732;
			
			// aapt resource value: 0x7f080017
			public const int playBtn = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int playerVw = 2131230737;
			
			// aapt resource value: 0x7f08000b
			public const int prevSong = 2131230731;
			
			// aapt resource value: 0x7f08000f
			public const int record = 2131230735;
			
			// aapt resource value: 0x7f080015
			public const int recordBtn = 2131230741;
			
			// aapt resource value: 0x7f08000a
			public const int songTitle = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int songsList = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int start = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int stop = 2131230721;
			
			// aapt resource value: 0x7f080018
			public const int stopBtn = 2131230744;
			
			// aapt resource value: 0x7f080003
			public const int textView1 = 2131230723;
			
			// aapt resource value: 0x7f080010
			public const int videoLt = 2131230736;
			
			// aapt resource value: 0x7f08001a
			public const int video_infoTvw = 2131230746;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AudioRecorder = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MusicMain = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Song = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int VideoMain = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int bensound_acousticbreeze = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bensound_happiness = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int bensound_sweet = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
